version: '3.8'

services:
  template_django_web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ..:/app
      # Volume persistente nomeado
      - django_db_data:/app/db
    # env_file:
    #   - ../.env
    ports:
      - "8031:8000"

# Volumes garante que os dados do banco de dados sejam mantidos persistentemente
volumes:
  # Declaração explícita do volume nomeado
  django_db_data: